### ISSUE TITLE
How to generate videos based on StableDiffusion v1.5

### ISSUE THREAD

**Issue by YBYBZhang** [guoyww/AnimateDiff#10]
Thanks for your great work! Could you provide scripts or configs to produce videos based on SD v1.5?

**Comment by YBYBZhang** [comment]
The weights of StableDiffusion v1.5 has been passed by `--pretrained_model_path`. Thus, I think the path to safetensors could be None, but got weird results :)

**Comment by actionless** [comment]
@YBYBZhang having the same issue with empty safetensors (the frames are not connected to each other)

did you figured it out?

**Comment by YBYBZhang** [comment]
@actionless Using SD v1.5 as base model still gets bad results :) I replace it with [Realistic Vision](https://civitai.com/models/4201/realistic-vision-v20).

**Comment by actionless** [comment]
@YBYBZhang not my case, as i intending to use customly-trained model

however after  few experiments, i've just realized that in such setup (MotionModule+base model only) it works the best when the both are of 1.5 or both sd 1.4 version - in that case result looks adequate
