### ISSUE TITLE
Any progress about I2V(image2video) ？ here's my results

### ISSUE THREAD

**Issue by ykk648** [guoyww/AnimateDiff#103]
![init_image](https://github.com/guoyww/AnimateDiff/assets/19514053/16c7079c-f6da-4316-aeca-e63b2c777529)

![sample](https://github.com/guoyww/AnimateDiff/assets/19514053/b8ece59f-54b1-4bab-b18d-7d038be4dbc6)

**Comment by patrolli** [comment]
Hello, may I ask if you could share how you did it? Do you need to fine-tune this motion module?

**Comment by Ainaemaet** [comment]
Yes, plz share. I2v and we can take the last frame of each for subsequent gens and maintain some continuity for longer shots.

**Comment by ykk648** [comment]
I think using AnimateDiff itself to do I2V mission is nearly impossiable as the motion module trained without init_image but init_video, the SD model can recognize the latent extracted from image but motion module cant.

I will release code tomorrow maybe.

**Comment by maximepeabody** [comment]
how did you get it to be so consistent with the input image? When I try this, I get a similar styled image, but there's some significant changes with the video vs the image

**Comment by b4rnn** [comment]
i thim i2v is a huge gamechanger

**Comment by ykk648** [comment]
code realeased on https://github.com/ykk648/AnimateDiff

**Comment by Bendito999** [comment]
A good repo and Gradio UI I've been doing image to video with that also includes the 'longer video' code,, is https://github.com/hoalarious/AnimateDiff  . It is work in progress though, but the author has been making good progress, I've been using it now instead of the old 'talesofai' one that didn't have a user interface.

**Comment by Ainaemaet** [comment]
> A good repo and Gradio UI I've been doing image to video with that also includes the 'longer video' code,, is https://github.com/hoalarious/AnimateDiff . It is work in progress though, but the author has been making good progress, I've been using it now instead of the old 'talesofai' one that didn't have a user interface.

Hello, I've been trying to get app.py in the repo you linked to work but keep getting an error and the author doesn't seem to be accepting any issue reports. 
Would you be able to help me figure out why it won't start? 

In that repo the inference runs fine in terminal via the provided samples codes and I get proper output in the 'output' folder,
but when trying to run 'python app.py' I get the following error:
python app.py Traceback (most recent call last): File "/home/myusername/ML/MC/AnimateDiff/app.py", line 651, in <module> demo = ui() File "/home/myusername/ML/MC/AnimateDiff/app.py", line 636, in ui generate_tab_ui() File "/home/myusername/ML/MC/AnimateDiff/app.py", line 475, in generate_tab_ui stable_diffusion_dropdown, motion_module_dropdown, checkpoint_dropdown = base_model_selection_ui() File "/home/myusername/ML/MC/AnimateDiff/app.py", line 416, in base_model_selection_ui value=controller.checkpoints_list[0], IndexError: list index out of range

I'm running it in anaconda WSL2 Ubuntu20.04, not sure if that makes a difference but I've been at this for days now and can't figure it out and I'm hoping someone better versed in python can give me a hand.

**Comment by maximepeabody** [comment]
> > A good repo and Gradio UI I've been doing image to video with that also includes the 'longer video' code,, is https://github.com/hoalarious/AnimateDiff . It is work in progress though, but the author has been making good progress, I've been using it now instead of the old 'talesofai' one that didn't have a user interface.
> 
> Hello, I've been trying to get app.py in the repo you linked to work but keep getting an error and the author doesn't seem to be accepting any issue reports. Would you be able to help me figure out why it won't start?
> 
> In that repo the inference runs fine in terminal via the provided samples codes and I get proper output in the 'output' folder, but when trying to run 'python app.py' I get the following error: python app.py Traceback (most recent call last): File "/home/myusername/ML/MC/AnimateDiff/app.py", line 651, in demo = ui() File "/home/myusername/ML/MC/AnimateDiff/app.py", line 636, in ui generate_tab_ui() File "/home/myusername/ML/MC/AnimateDiff/app.py", line 475, in generate_tab_ui stable_diffusion_dropdown, motion_module_dropdown, checkpoint_dropdown = base_model_selection_ui() File "/home/myusername/ML/MC/AnimateDiff/app.py", line 416, in base_model_selection_ui value=controller.checkpoints_list[0], IndexError: list index out of range
> 
> I'm running it in anaconda WSL2 Ubuntu20.04, not sure if that makes a difference but I've been at this for days now and can't figure it out and I'm hoping someone better versed in python can give me a hand.

do you have all the models downloaded in the correct models directory? You need to download the checkpoints into that directory

**Comment by Ainaemaet** [comment]
I thought I did, but looking at another comment here today I think I may have a few in the wrong place. 

Thanks for the suggestion, I'll give it a try and let ya'll know. :)

**Comment by Ainaemaet** [comment]
Ok, I installed all the models according to this repos instructions (and a few of the comments that gave suggestions on where they should go) and still having the same error.

**Comment by maximepeabody** [comment]
can you share what your models/ dir looks like now?

**Comment by Ainaemaet** [comment]
Ok, I'm all good now. Somehow I got things mixed up and got some models in everywhere but the checkpoints folder. I copied a couple over and all looks well now. :) 

Thanks again for the help, really looking forwards to trying this out outside of the a1111 extension, as the extension seems rather limited compared to some of the AnimateDiff forks out there.

**Comment by Ainaemaet** [comment]
Only difficulty I'm having now is using the --listen flag. The way I have my WSL2 setup, I have to allow traffic with netsh to specific ip and port - usually with gradio I use --listen and then I can access outside of wsl using a browser in windows, but this doesn't seem to be working here.

**Comment by kiqir** [comment]
What is the reason why an init-image animation may not work? It generates a new animation and it doesn't animate the init-image.

**Comment by ykk648** [comment]
@kiqir  I'm sure demo codes works well for me, as no more progress on I2V for now , issue close

**Comment by b4rnn** [comment]
im working on an image-to-video generator startup, is it a good idea?

**Comment by kiqir** [comment]
I'm really sorry but I want to give you an example of my problem.
This is output:
![image (4)](https://github.com/guoyww/AnimateDiff/assets/113307056/43e2b407-c947-4029-a74e-86d90f21b127)
This is settings in gradio interface:
![2023-08-15_23-50-40](https://github.com/guoyww/AnimateDiff/assets/113307056/8697a79b-66cf-47c7-a7bb-10c9a19d3199)

What did I do wrong?

**Comment by ykk648** [comment]
@b4rnn Animatediff proved that SD can generate sequence video with some kind of supervision, now we only have to add a image supervision to the training process or diffusion network, the image can be replaced by optical-flow/depth map/vae embedding etc.

**Comment by ykk648** [comment]
@kiqir this is truly what https://github.com/continue-revolution/sd-webui-animatediff can give to you, raise an issue to https://github.com/continue-revolution/sd-webui-animatediff if you have quesion about that, the design of it do have some problems though, I doubt no one is working on it.
