### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by zcdliuwei** [guoyww/AnimateDiff#108]
When I use another base model: rcnzCartoon3d_v20Inpainting.safetensors, without using Lora, 
I received the following error report：
Error(s) in loading state_dict for UNet3DConditionModel:\\n\\tsize mismatch for conv_in.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).
May I ask how to resolve this error

**Comment by alinrdinn** [comment]
same here. did you find any solution?
