### ISSUE TITLE
Different frame rates across videos (24 fps, 30 fps, 60 fps) in the WebVid

### ISSUE THREAD

**Issue by ykk648** [guoyww/AnimateDiff#123]
Did you simply sample frames on interval 4 regardless frame rate?

refer https://github.com/YingqingHe/LVDM/issues/4

**Comment by haofanwang** [comment]
Also, as the model is trained on 256x256, what is the original video size (360P, 720P, ...)?

**Comment by ykk648** [comment]
https://github.com/guoyww/AnimateDiff/blob/e816747d661bffc4c709f16975a4dc4a897ba4bd/animatediff/data/dataset.py#L48
