### ISSUE TITLE
How to load lora model

### ISSUE THREAD

**Issue by LiuShiyu95** [guoyww/AnimateDiff#124]
Hi, Thank you for your great job!

I tried to load some models on Civitai, but some can be read, but the Lora model cannot be read correctly. How can I solve this problem?

`KeyError: 'encoder.conv_in.weight'`

**Comment by noparkee** [comment]
Hello. I'm having the same issue.
How did you solve the problem?

**Comment by Nisnaica** [comment]
Same problem... Please help!

**Comment by JoshonSmith** [comment]
Same problem in sdxl branch
