### ISSUE TITLE
Collab error

### ISSUE THREAD

**Issue by sinaflair** [guoyww/AnimateDiff#125]
Hi i'm using the collab link from this repo but i get this error when i run it
/content/animatediff
2023-08-21 13:47:11.130301: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
loaded temporal unet's pretrained weights from /content/animatediff/models/StableDiffusion/unet ...
### Temporal Module Parameters: 417.1376 M
current seed: 10917152860782582783
sampling dark shot, epic realistic, portrait of halo, sunglasses, blue eyes, tartan scarf, white hair by atey ghailan, by greg rutkowski, by greg tocchini, by james gilleard, by joe fenton, by kaethe butcher, gradient yellow, black, brown and magenta color scheme, grunge aesthetic!!! graffiti tag wall background, art by greg rutkowski and artgerm, soft cinematic light, adobe lightroom, photolab, hdr, intricate, highly detailed, depth of field, faded, neutral colors, hdr, muted colors, hyperdetailed, artstation, cinematic, warm lights, dramatic light, intricate details, complex background, rutkowski, teal and orange ...
Token indices sequence length is longer than the specified maximum sequence length for this model (139 > 77). Running this sequence through the model will result in indexing errors
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['artgerm, soft cinematic light, adobe lightroom, photolab, hdr, intricate, highly detailed, depth of field, faded, neutral colors, hdr, muted colors, hyperdetailed, artstation, cinematic, warm lights, dramatic light, intricate details, complex background, rutkowski, teal and orange']
100% 25/25 [04:02<00:00,  9.68s/it]
100% 16/16 [00:06<00:00,  2.64it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/animatediff/scripts/animate.py", line 159, in <module>
    main(args)
  File "/content/animatediff/scripts/animate.py", line 137, in main
    save_videos_grid(sample, f"{savedir}/sample/{sample_idx}-{prompt}.gif")
  File "/content/animatediff/animatediff/utils/util.py", line 25, in save_videos_grid
    imageio.mimsave(path, outputs, fps=fps)
  File "/usr/local/lib/python3.10/dist-packages/imageio/v2.py", line 495, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/imageio/plugins/pillow.py", line 383, in write
    raise TypeError(
TypeError: The keyword `fps` is no longer supported. Use `duration`(in ms) instead, e.g. `fps=50` == `duration=20` (1000 * 1/50).

**Comment by Archilles07** [comment]
Did you sort out?? If not here:
replace 'fps=8' with 'duration=125'  //in line: 13
and
'duration=duration' instead of 'fps=fps' //in line: 25
u can find both of these in '/content/animatediff/animatediff/utils/util.py' 
do  this and it will work although it's not official so wait for the author fix

**Comment by sinaflair** [comment]
Thanks, it worked!
