### ISSUE TITLE
Controlnet for AnimeteDIff

### ISSUE THREAD

**Issue by TheDenk** [guoyww/AnimateDiff#131]
Hi :) Thanks for good repository.
I've added controlnet to your generation pipeline: https://github.com/TheDenk/ControledAnimateDiff
Also controlnet was added to the Gradio Demo.
I've update libraries version and change some code.
So, could I make pull request in your dev branch or you could create new branch? @guoyww 

**Some examples**
Original Video:
![|256](https://github.com/guoyww/AnimateDiff/assets/21247615/38425b97-5b84-4469-b873-5a625060ecda)
Processed Video:
![dance_1girl](https://github.com/guoyww/AnimateDiff/assets/21247615/79006f29-f8fb-4a43-aa9f-c16a2a5cbf82)

or depth mask:
![smiling_depth_16_2](https://github.com/guoyww/AnimateDiff/assets/21247615/cff90790-bd8a-488d-bb40-a3b4da289a4f)
processed:
![smiling_forbidden_castle](https://github.com/guoyww/AnimateDiff/assets/21247615/65a7468f-5b7e-4dbe-90db-0e037a4df28f)

**Comment by TheDenk** [comment]
@huxiuhan @doubledaibo @limbo0000 @AnyiRao Could anybody help?)

**Comment by limbo0000** [comment]
Thanks for such a wonderful feature! Surely,you could make a pr on dev branch and let's see how to merge it quickly.

**Comment by kingnobro** [comment]
Hi, can this Controlnet do [reference-only](https://github.com/Mikubill/sd-webui-controlnet/pull/1235) generation?
I know some people have made AnimateDiff to support the initial image. However, this is ad hoc since different initial images may need different alpha blending ratios. So, I want to try reference-only control. I try to incorporate [MasaCtrl](https://github.com/TencentARC/MasaCtrl) into AnimateDiff, but it seems difficult.

**Comment by TheDenk** [comment]
> Hi, can this Controlnet do [reference-only](https://github.com/Mikubill/sd-webui-controlnet/pull/1235) generation? I know some people have made AnimateDiff to support the initial image. However, this is ad hoc since different initial images may need different alpha blending ratios. So, I want to try reference-only control. I try to incorporate [MasaCtrl](https://github.com/TencentARC/MasaCtrl) into AnimateDiff, but it seems difficult.

Hi, @kingnobro  :)
I have not made this yet. Maybe later if it's in demand.

**Comment by pikeyang** [comment]
Is the character's movement generated based on the conditions of the controlnet?

**Comment by TheDenk** [comment]
> Is the character's movement generated based on the conditions of the controlnet?

yes it is

**Comment by pikeyang** [comment]
> > Is the character's movement generated based on the conditions of the controlnet?
> 
> yes it is

Does it support ip adapter?

**Comment by Affegithub** [comment]
> > Hi, can this Controlnet do [reference-only](https://github.com/Mikubill/sd-webui-controlnet/pull/1235) generation? I know some people have made AnimateDiff to support the initial image. However, this is ad hoc since different initial images may need different alpha blending ratios. So, I want to try reference-only control. I try to incorporate [MasaCtrl](https://github.com/TencentARC/MasaCtrl) into AnimateDiff, but it seems difficult.
> 
> 
> 
> Hi, @kingnobro  :)
> 
> I have not made this yet. Maybe later if it's in demand.

I eager reference-only for Controlnet in Comfy UI too. I'm using Reference-Only-Simple node for instead with AnimateDiff but it returns error when it tried to fetch more than 16 frames(batches). So, I want you to make new control-net that can clear this issue.
