### ISSUE TITLE
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'models/StableDiffusion/stable-diffusion-v1-5'. Use `repo_type` argument if needed.

### ISSUE THREAD

**Issue by dancemanUK** [guoyww/AnimateDiff#14]
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'models/StableDiffusion/stable-diffusion-v1-5'. Use `repo_type` argument if needed.

(animatediff) G:\AI\AnimateDiff>

win10 conda3 pytorch2.01 cuda118. 
模型都下好，放在G:\AI\AnimateDiff\models\StableDiffusion,文件名为stable-diffusion-v1-5 .safetensors. 还是报这个错误。

**Comment by sdbds** [comment]
same problem

**Comment by dancemanUK** [comment]
> same problem

青龙大佬，改文件animate.py,约是第150行。
    parser.add_argument("--pretrained_model_path", type=str, default="models/StableDiffusion/stable-diffusion-v1-5.safetensors",)

**Comment by dancemanUK** [comment]
其它路径这样子，修写。在win10下面。
  ### >>> create validation pipeline >>> ###
           # tokenizer    = CLIPTokenizer.from_pretrained(args.pretrained_model_path, subfolder="tokenizer")
            tokenizer    = CLIPTokenizer.from_pretrained("G:\\AI\\AnimateDiff\\models\\StableDiffusion\\tokenizer\\")
           # text_encoder = CLIPTextModel.from_pretrained(args.pretrained_model_path, subfolder="text_encoder")
            text_encoder = CLIPTextModel.from_pretrained("G:\\AI\\AnimateDiff\\models\\StableDiffusion\\text_encoder\\")
           # vae          = AutoencoderKL.from_pretrained(args.pretrained_model_path, subfolder="vae")
            vae          = AutoencoderKL.from_pretrained("G:\\AI\\AnimateDiff\\models\\StableDiffusion\\vae\\")                  
           # unet         = UNet3DConditionModel.from_pretrained_2d(args.pretrained_model_path, subfolder="unet", unet_additional_kwargs=OmegaConf.to_container(inference_config.unet_additional_kwargs))
            unet         = UNet3DConditionModel.from_pretrained_2d("G:\\AI\\AnimateDiff\\models\\StableDiffusion\\unet\\", unet_additional_kwargs=OmegaConf.to_container(inference_config.unet_additional_kwargs))

**Comment by aartykov** [comment]
Try setting "parser.add_argument("--pretrained_model_path", type=str, default="models/StableDiffusion/stable-diffusion-v1-5.safetensors",) " default path to "models/StableDiffusion". It should solve your problem.

**Comment by 796F** [comment]
`models/StableDiffusion` worked for me.  it resolved all model path issues, the other recommendations didn't work.  thanks aartykov

**Comment by zhanghongyong123456** [comment]
> `models/StableDiffusion` worked for me. it resolved all model path issues, the other recommendations didn't work. thanks aartykov

Error caused by path mismatch，
in code  ： parser.add_argument("--pretrained_model_path", type=str, default="models/StableDiffusion/stable-diffusion-v1-5",)
![image](https://github.com/guoyww/AnimateDiff/assets/48466610/e143d950-ab89-4f6b-9a76-a955164cefeb)

but  in file： StableDiffusion  name 
Need to specify the correct path
like this
![image](https://github.com/guoyww/AnimateDiff/assets/48466610/585f7496-1217-4a5d-b3a7-1aaa7f5b77b7)

**Comment by Cubey42** [comment]
If I change the path to be a directory I get:
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models/StableDiffusion.

but If I set it to a specific file I get:
ValueError: Calling CLIPTokenizer.from_pretrained() with the path to a single file or url is not supported for this tokenizer. Use a model identifier or the path to a directory instead.

**Comment by RexLeeGrey** [comment]
Configured all afternoon and still can't solve the problem, is this something you don't want people to use?

**Comment by Ainaemaet** [comment]
@RexLeeGrey couldn't agree more. I appreciate the work but the instructions are sorely lacking and so many issues without solutions. 

I've been at it for 3 days and still can't get it figured out. Running WSL2 and every single time I solve one error there is another. 


Haven't had this much trouble with any other app. :/

**Comment by WainWong** [comment]
> 其它路径这样子，修写。在win10下面。
> 
> ### >>> create validation pipeline >>>
> >>> 创建验证管道 >>>
> ```
>        # tokenizer    = CLIPTokenizer.from_pretrained(args.pretrained_model_path, subfolder="tokenizer")
>         tokenizer    = CLIPTokenizer.from_pretrained("G:\\AI\\AnimateDiff\\models\\StableDiffusion\\tokenizer\\")
>        # text_encoder = CLIPTextModel.from_pretrained(args.pretrained_model_path, subfolder="text_encoder")
>         text_encoder = CLIPTextModel.from_pretrained("G:\\AI\\AnimateDiff\\models\\StableDiffusion\\text_encoder\\")
>        # vae          = AutoencoderKL.from_pretrained(args.pretrained_model_path, subfolder="vae")
>         vae          = AutoencoderKL.from_pretrained("G:\\AI\\AnimateDiff\\models\\StableDiffusion\\vae\\")                  
>        # unet         = UNet3DConditionModel.from_pretrained_2d(args.pretrained_model_path, subfolder="unet", unet_additional_kwargs=OmegaConf.to_container(inference_config.unet_additional_kwargs))
>         unet         = UNet3DConditionModel.from_pretrained_2d("G:\\AI\\AnimateDiff\\models\\StableDiffusion\\unet\\", unet_additional_kwargs=OmegaConf.to_container(inference_config.unet_additional_kwargs))
> ```

it work，thanks

**Comment by guoti777** [comment]
错误原因是：手动下的配置文件浏览器会自动修改名字（添加前缀），如tokenizer文件夹中的vocab.json被修改为“tokenizer_vocab.json”。（这个前缀就是所在文件夹的名字）
解决办法：手动修改回就可以了。亲测可用。
官方代码没有问题的，不用修改。

**Comment by LIANGSHUOWEN** [comment]
> 这个

it works for me， thanks！！！

**Comment by LIANGSHUOWEN** [comment]
> 错误原因是：手动下的配置文件浏览器会自动修改名字（添加前缀），如tokenizer文件夹中的vocab.json被修改为“tokenizer_vocab.json”。（这个前缀就是所在文件夹的名字） 解决办法：手动修改回去就可以了。亲测可用。 官方代码没有问题的，不用修改。
it works for me， thanks！！！
