### ISSUE TITLE
I got  size mismatch erro when i use v2 ckpt

### ISSUE THREAD

**Issue by nanjingzhouyu** [guoyww/AnimateDiff#147]
Traceback (most recent call last):
  File "D:\ENV\anidiff\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ENV\anidiff\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\AIGC1\AnimateDiff\scripts\animate.py", line 159, in <module>
    main(args)
  File "D:\AIGC1\AnimateDiff\scripts\animate.py", line 67, in main
    missing, unexpected = pipeline.unet.load_state_dict(motion_module_state_dict, strict=False)
  File "D:\ENV\anidiff\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet3DConditionModel:
        size mismatch for down_blocks.0.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
        size mismatch for down_blocks.0.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
        size mismatch for down_blocks.0.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
        size mismatch for down_blocks.0.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
        size mismatch for down_blocks.1.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
        size mismatch for down_blocks.1.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
        size mismatch for down_blocks.1.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
        size mismatch for down_blocks.1.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
        size mismatch for down_blocks.2.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for down_blocks.2.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for down_blocks.2.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for down_blocks.2.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for down_blocks.3.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for down_blocks.3.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for down_blocks.3.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for down_blocks.3.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for up_blocks.0.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for up_blocks.0.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for up_blocks.0.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for up_blocks.0.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for up_blocks.0.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for up_blocks.0.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for up_blocks.1.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for up_blocks.1.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for up_blocks.1.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for up_blocks.1.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for up_blocks.1.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for up_blocks.1.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
        size mismatch for up_blocks.2.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
        size mismatch for up_blocks.2.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
        size mismatch for up_blocks.2.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
        size mismatch for up_blocks.2.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
        size mismatch for up_blocks.2.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
        size mismatch for up_blocks.2.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
        size mismatch for up_blocks.3.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
        size mismatch for up_blocks.3.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
        size mismatch for up_blocks.3.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
        size mismatch for up_blocks.3.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
        size mismatch for up_blocks.3.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
        size mismatch for up_blocks.3.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).

**Comment by nanjingzhouyu** [comment]
can anyone help?

**Comment by zhanghongyong123456** [comment]
> can anyone help?

you need  set   config for patch:   inference-v1.yaml --->v2.yaml
https://github.com/guoyww/AnimateDiff/blob/1904a01117824d7d294227059f6b684972c5a8b6/scripts/animate.py#L151C39-L151C39

**Comment by nanjingzhouyu** [comment]
> > can anyone help?
> 
> you need set config for patch: inference-v1.yaml --->v2.yaml https://github.com/guoyww/AnimateDiff/blob/1904a01117824d7d294227059f6b684972c5a8b6/scripts/animate.py#L151C39-L151C39

Thank you! it  works
