### ISSUE TITLE
Please add init image support

### ISSUE THREAD

**Issue by SoftologyPro** [guoyww/AnimateDiff#150]
Could you please merge the init code from
https://github.com/talesofai/AnimateDiff
with the next update?  It would be great to be able to specify a seed image with this main repo code and not have to use a fork (that doees not have the latest v2 support).

**Comment by Gitterman69** [comment]
yes please! init img is a must

**Comment by gordingus** [comment]
Also interested in this feature! Was super fun to play with

**Comment by DoctorDiffusion** [comment]
Yes please! img2vid would be an outstanding addison.

**Comment by realsammyt** [comment]
great idea

**Comment by limbo0000** [comment]
We are working on that:)

**Comment by Gitterman69** [comment]
> We are working on that:)

any eta? 🤞

**Comment by powerspowers** [comment]
we are working with a version that includes it but trying to get it working exactly right to take the initial image + the given prompt in combination to set the video in the right direction. Definitely a challenge! Will contribute if we get the balance right.

**Comment by SoftologyPro** [comment]
> I did some work https://github.com/ykk648/AnimateDiff

There are already some forks that support an init image.  See my first link above.  Yours does look good too.
I am really asking for support to be added into this main repo.  That way as this goes forward and gets updated the init image changes are not lost.

**Comment by powerspowers** [comment]
@ykk648 your effort does look promising but it sounds like you ran into some fundamental block in getting it fully there in AD?

@SoftologyPro we tried a couple forks and so far none of them seemed to power using an input image as a true start frame, finding it in the latent space and then animating it by itself of with and added prompt. Best we got was using the image as the initial diffused image. Did you see anything better in one or more forks?

**Comment by SoftologyPro** [comment]
> @SoftologyPro we tried a couple forks and so far none of them seemed to power using an input image as a true start frame, finding it in the latent space and then animating it by itself of with and added prompt. Best we got was using the image as the initial diffused image. Did you see anything better in one or more forks?
> 

I didn't try any of the forks myself. I just got requests to add init image support and thought rather than supporting a different fork it would be better to have the change made to the original repo. I have added support for AnimateDiff in Visions of Chaos and a few users suggested seed image and pointed to that first repo I linked to. I tried to merge those changes in (unsuccessfully) so that is when I opened this issue.

**Comment by JoshonSmith** [comment]
We are working on that:)

**Comment by TheOneTrueGuy** [comment]
It says issue is completed but I can't find anything in the docs about how to use it.
