### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for AutoencoderKL:

### ISSUE THREAD

**Issue by KyleYueye** [guoyww/AnimateDiff#154]
I encountered this error in inference.
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/code/AnimateDiff/scripts/animate.py", line 163, in <module>
    main(args)
  File "/home/ubuntu/code/AnimateDiff/scripts/animate.py", line 97, in main
    pipeline.vae.load_state_dict(converted_vae_checkpoint)
  File "/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
        Missing key(s) in state_dict: "encoder.mid_block.attentions.0.to_q.weight", "encoder.mid_block.attentions.0.to_q.bias", "encoder.mid_block.attentions.0.to_k.weight", "encoder.mid_block.attentions.0.to_k.bias", "encoder.mid_block.attentions.0.to_v.weight", "encoder.mid_block.attentions.0.to_v.bias", "encoder.mid_block.attentions.0.to_out.0.weight", "encoder.mid_block.attentions.0.to_out.0.bias", "decoder.mid_block.attentions.0.to_q.weight", "decoder.mid_block.attentions.0.to_q.bias", "decoder.mid_block.attentions.0.to_k.weight", "decoder.mid_block.attentions.0.to_k.bias", "decoder.mid_block.attentions.0.to_v.weight", "decoder.mid_block.attentions.0.to_v.bias", "decoder.mid_block.attentions.0.to_out.0.weight", "decoder.mid_block.attentions.0.to_out.0.bias". 
        Unexpected key(s) in state_dict: "encoder.mid_block.attentions.0.key.bias", "encoder.mid_block.attentions.0.key.weight", "encoder.mid_block.attentions.0.proj_attn.bias", "encoder.mid_block.attentions.0.proj_attn.weight", "encoder.mid_block.attentions.0.query.bias", "encoder.mid_block.attentions.0.query.weight", "encoder.mid_block.attentions.0.value.bias", "encoder.mid_block.attentions.0.value.weight", "decoder.mid_block.attentions.0.key.bias", "decoder.mid_block.attentions.0.key.weight", "decoder.mid_block.attentions.0.proj_attn.bias", "decoder.mid_block.attentions.0.proj_attn.weight", "decoder.mid_block.attentions.0.query.bias", "decoder.mid_block.attentions.0.query.weight", "decoder.mid_block.attentions.0.value.bias", "decoder.mid_block.attentions.0.value.weight". 
```

**Comment by neurowelt** [comment]
I've been trying to hack through the code to get it running on `diffusers` v.0.21.3 and I also confronted this one. For now it seems as [this simple renaming](https://github.com/neurowelt/AnimateDiff/commit/f776285beb39c61bd3ecfdf39a590d7ab00e8b37) will do (I got a fork working on 0.21.3 with several other improvements [here](https://github.com/neurowelt/AnimateDiff)), but I would look forward to checking up the [`animatediff.utils.convert_from_ckpt.convert_ldm_vae_checkpoint`](https://github.com/guoyww/AnimateDiff/blob/a3b0bee4d77983cf132f60ba452c0c4088e50997/animatediff/utils/convert_from_ckpt.py#L559). I've been kind of speedy with this, so I didn't get to more detail into reworking it for newer `AutoencoderK` version.

**Comment by KyleYueye** [comment]
> I've been trying to hack through the code to get it running on `diffusers` v.0.21.3 and I also confronted this one. For now it seems as [this simple renaming](https://github.com/neurowelt/AnimateDiff/commit/f776285beb39c61bd3ecfdf39a590d7ab00e8b37) will do (I got a fork working on 0.21.3 with several other improvements [here](https://github.com/neurowelt/AnimateDiff)), but I would look forward to checking up the [`animatediff.utils.convert_from_ckpt.convert_ldm_vae_checkpoint`](https://github.com/guoyww/AnimateDiff/blob/a3b0bee4d77983cf132f60ba452c0c4088e50997/animatediff/utils/convert_from_ckpt.py#L559). I've been kind of speedy with this, so I didn't get to more detail into reworking it for newer `AutoencoderK` version.

Hello, have you ever encountered this error? 
`TypeError: BasicTransformerBlock.set_use_memory_efficient_attention_xformers() takes 2 positional arguments but 3 were given`

**Comment by neurowelt** [comment]
Yes, if comes from the fact that newer `diffusers` versions changed this method. You can see a solution [here](https://github.com/camenduru/AnimateDiff/commit/9e4fec0d737437c4a026cf3a9cd3ed22f2c67769) 😊

**Comment by KyleYueye** [comment]
@neurowelt Sincerely thanks for ur help. Following ur fix-commits helps me a lot. ❤️🤝
