### ISSUE TITLE
Missing Error with Xformers

### ISSUE THREAD

**Issue by Fade07w** [guoyww/AnimateDiff#165]
Having a issue with Xformers at the opening of Comfy.  Unsure of how to fix this.

[AnimateDiff] - WARNING - xformers is enabled but it has a bug that can cause issue while using with AnimateDiff.ormers and

**Comment by bkxgene** [comment]
I also have the same error.

**Comment by yuema419** [comment]
yes ,i also the same error, How to solve this problem, thanks

**Comment by nieli123456** [comment]
I also have the same error.
