### ISSUE TITLE
Abandoning text model

### ISSUE THREAD

**Issue by powerspowers** [guoyww/AnimateDiff#176]
This is just some feedback stemming from the addition of the motion LoRAs. I would argue that keeping cinematography and camera motion in the main motion training + adding the keywords to the main text model is better than breaking out motion plugins / LoRAs. Camera motion is central to video description and generation so breaking it out as additional parameters sent in with a prompt is antithetical to prompt to video generation as a whole. It also favors parameter driven tools vs generally accessible prompt and chat systems. I know there is a divide on whether prompt engineering is the best approach to visual AI but I think the 2D generative world is proving that text to image is impressive and powerful, and more 'trainable' with prompt setups than parameter based APIs. 

This issue post is to advocate for adding cinematography, camera motion and other video actions to the main motion training vs breaking them out as modules with parameters. I think moving away from the prompt approach leaves open source video vulnerable to closed source generators that are doubling down on language models for video. IMHO

**Comment by b4rnn** [comment]
im working on an image-to-video model

> This is just some feedback stemming from the addition of the motion LoRAs. I would argue that keeping cinematography and camera motion in the main motion training + adding the keywords to the main text model is better than breaking out motion plugins / LoRAs. Camera motion is central to video description and generation so breaking it out as additional parameters sent in with a prompt is antithetical to prompt to video generation as a whole. It also favors parameter driven tools vs generally accessible prompt and chat systems. I know there is a divide on whether prompt engineering is the best approach to visual AI but I think the 2D generative world is proving that text to image is impressive and powerful, and more 'trainable' with prompt setups than parameter based APIs.
> 
> This issue post is to advocate for adding cinematography, camera motion and other video actions to the main motion training vs breaking them out as modules with parameters. I think moving away from the prompt approach leaves open source video vulnerable to closed source generators that are doubling down on language models for video. IMHO

im working on an image-to-video model
