### ISSUE TITLE
Google Collab

### ISSUE THREAD

**Issue by Niutonian** [guoyww/AnimateDiff#18]
Hello, I really want to try AnimateDiff, 
sadly I only have an 8Gb RTX 3070,

Do you think you will ever release a notebook? 
Thanks

**Comment by guoyww** [comment]
Hi @Niutonian , you may try this repo: https://github.com/camenduru/AnimateDiff-colab

**Comment by limbo0000** [comment]
I will close this issue. Feel free to reopen it if there is any other issue.
