### ISSUE TITLE
Irregularly Shaped Cells in Output Image Using AnimateDiff

### ISSUE THREAD

**Issue by alinrdinn** [guoyww/AnimateDiff#196]
Hello,

I've been using the `AnimateDiff` function in the `nitrosocke/Ghibli-Diffusion` repository for my project. However, I've encountered an issue where the output image consists of irregularly shaped cells, which is not the result I expected.

Initially, I thought this might be due to the base model I was using (`runwayml/stable-diffusion-v1-5`), so I switched to using `nitrosocke/Ghibli-Diffusion` as the base model. Unfortunately, the problem persists even after changing the base model.

I'm not sure why this is happening and would appreciate any guidance or suggestions to resolve this issue. 

Thank you for your time and assistance.

Here is my result:

![913a3da6-ed63-4873-bdfe-1a082508daec](https://github.com/guoyww/AnimateDiff/assets/54460857/248f54af-aa2f-461a-a191-c0e8a287b035)

**Comment by GuruVirus** [comment]
AnimateDiff only works at best quality on realistic models and is probably breaking down. Try a different prompt. As the paper says, "Failure cases[:] Our method cannot produce proper motions when the personalized domain is far from realistic... e.g., 2D Disney cartoon"
