### ISSUE TITLE
Problem with stable-diffusion-v1-5

### ISSUE THREAD

**Issue by Siziff** [guoyww/AnimateDiff#197]
I can't understand how to correctly download stable-diffusion-v1-5 rep. , every time I get this error and I have no idea how to fix it :/

`OSError: Can't load tokenizer for '/dsk1/ivan/AnimateDiff/models/stable-diffusion-v1-5'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/dsk1/ivan/AnimateDiff/models/stable-diffusion-v1-5' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.`

I tried to do this:

git lfs install
git clone https://huggingface.co/runwayml/stable-diffusion-v1-5 models/StableDiffusion/

or 

git lfs install
git clone --branch fb1  https://huggingface.co/runwayml/stable-diffusion-v1-5

**Comment by KKN18** [comment]
Can you share how you solved this issue? I'm getting same error :(

**Comment by thisisiron** [comment]
try this:
```
cd models/StableDiffusion/stable-diffusion-v1-5
git lfs pull
```
