### ISSUE TITLE
Extension for Auto1111?

### ISSUE THREAD

**Issue by mischaschaub** [guoyww/AnimateDiff#2]
May we hope that you will offer this great functionality as an extension in for stable diffusion webui?

**Comment by thezveroboy** [comment]
I'm also looking forward to this extension. As I understand, it can be run on GPUs with 12 gigabytes of video memory. And that's already a great reason to create an extension. Thank you!

**Comment by anastasiuspernat** [comment]
Yeah, looking forward to it too! That will allow controlnet, advanced prompting with brackets, external VAEs etc! Thank you.

**Comment by continue-revolution** [comment]
I am the author of the [SAM extension](https://github.com/continue-revolution/sd-webui-segment-anything) and I wrote one extension for AnimateDiff. https://github.com/continue-revolution/sd-webui-animatediff
