### ISSUE TITLE
(base) C:\AnimateDiff>conda env create -f environment.yaml Collecting package metadata (repodata.json): done Solving environment: failed  ResolvePackageNotFound:   - xformers

### ISSUE THREAD

**Issue by protector131090** [guoyww/AnimateDiff#20]
(base) C:\AnimateDiff>conda env create -f environment.yaml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - xformers
  
  pip install xformers didnt help

**Comment by limbo0000** [comment]
As stated, please install xformers first to reduce the inference memory.

**Comment by protector131090** [comment]
> As stated, please install xformers first to reduce the inference memory.

but pip install xformers dosnt help, after installed xformers i still get the error

**Comment by limbo0000** [comment]
The error said: not found that package. That is, xformer is not successfully installed. I guess you can follow the readme of xformer and ensure it could be successfully installed.

**Comment by Jongulo** [comment]
I'm fairly certain the problem is that Conda can't install xformers on windows. Using pip to install xformers hasn't solved this for me either.

**Comment by protector131090** [comment]
> I'm fairly certain the problem is that Conda can't install xformers on windows. Using pip to install xformers hasn't solved this for me either.

I did manage to fix the issue. Opened the environment yaml file and deleted Xformers from conda - and added it to pip

**Comment by Jongulo** [comment]
> > I'm fairly certain the problem is that Conda can't install xformers on windows. Using pip to install xformers hasn't solved this for me either.
> 
> I did manage to fix the issue. Opened the environment yaml file and deleted Xformers from conda - and added it to pip

I tried this but got an error that xformers was built for a different version of pytorch, which xformers version did you install?
