### ISSUE TITLE
AttributeError: module 'comfy.model_management' has no attribute 'maximum_batch_area'

### ISSUE THREAD

**Issue by ultimatech-cn** [guoyww/AnimateDiff#220]
Just update comyUI, when I restart, I got following error message:
 File "E:\Comfy _ 1\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Comfy _ 1\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff\__init__.py", line 2, in <module>    from .animatediff.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\Comfy _ 1\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff\animatediff\nodes.py", line 16, in <module>
    from .sampler import AnimateDiffSampler, AnimateDiffSlidingWindowOptions
  File "E:\Comfy _ 1\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff\animatediff\sampler.py", line 57, in <module>
    orig_maximum_batch_area = model_management.maximum_batch_area
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.model_management' has no attribute 'maximum_batch_area'

Any workaround for this?

**Comment by zhanghongyong123456** [comment]
> Just update comyUI, when I restart, I got following error message: File "E:\Comfy _ 1\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "E:\Comfy _ 1\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff__init__.py", line 2, in from .animatediff.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS File "E:\Comfy _ 1\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff\animatediff\nodes.py", line 16, in from .sampler import AnimateDiffSampler, AnimateDiffSlidingWindowOptions File "E:\Comfy _ 1\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff\animatediff\sampler.py", line 57, in orig_maximum_batch_area = model_management.maximum_batch_area ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'comfy.model_management' has no attribute 'maximum_batch_area'
> 
> Any workaround for this?

Only  Update the latest version  （Comfyui and  ComfyUI-AnimateDiff-Evolved ）

**Comment by gaodianzhuo** [comment]
same error

**Comment by patientx** [comment]
same error with both animated-diff and / or evolved

**Comment by nekokun** [comment]
Got the same error, seems to be in commit dd4ba68b6e93a562d9499eff34e50dbbbc8714e7 from comfyui.
For now you can revert to commit 2c9dba8dc08eb35d29dab691c1f2808f6c9191ea this should make everything work again.

**Comment by lord-lethris** [comment]
same here

**Comment by ultimatech-cn** [comment]
Solved  by updating to the latest version.
