### ISSUE TITLE
The sdxl branch has a problem with the code that loads the LORA model

### ISSUE THREAD

**Issue by JoshonSmith** [guoyww/AnimateDiff#241]
文件：[animatediff](https://github.com/guoyww/AnimateDiff/tree/sdxl/animatediff)/[utils]/[util.py](https://github.com/guoyww/AnimateDiff/tree/sdxl/animatediff/utils/util.py)

    # Load LoRA
    if lora_path != "":
        lora_state_dict = {}
        with safe_open(lora_path, framework='pt', device='cpu') as f:
            for k in f.keys():
                lora_state_dict[k] = f.get_tensor(k)
        for k, v in lora_state_dict.items():
            if 'lora.up' in k:
			
                down_key = k.replace('lora.up', 'lora.down')
                if 'to_out' not in k:
                    original_key = k.replace('processor.', '').replace('_lora.up', '')
                else:
                    original_key = k.replace('processor.', '').replace('_lora.up', '.0')
                pipeline.unet.state_dict()[original_key] += lora_alpha * torch.mm(v, lora_state_dict[down_key])
        print(f'Loading lora model from {lora_path}')

if 'lora.up' in k:一直不会执行，尝试了几个lora模型

**Comment by JeffreyYzh** [comment]
hello, have you solved the problem?
