### ISSUE TITLE
beta_schedule

### ISSUE THREAD

**Issue by Artiprocher** [guoyww/AnimateDiff#246]
In AnimateDiff v2, some parameters in the scheduler are modified. For example, `beta_schedule` is `linear`, but this parameter is `scaled_linear` in the original version of `diffusers`.

This modification influences the amount of noise in every denoising step, thus it is inconsistent with most personalized T2I models.

Moreover, I notice that this parameter is also `linear` in the original `latent diffusion` repo, but it corresponds to a different behavior.

Did you make some mistakes when developing AnimateDiff v2?

**Comment by Artiprocher** [comment]
Sorry, I find you mentioned this in your paper.

**Comment by yuanzhi-zhu** [comment]
@Artiprocher hi, could you please tell me where in the paper you find the related words?

**Comment by yuanzhi-zhu** [comment]
oh nvm, I found it in the v1 version on arxiv
