### ISSUE TITLE
[v1]-missing keys: 560

### ISSUE THREAD

**Issue by song-wensong** [guoyww/AnimateDiff#256]
```
loaded 3D unet's pretrained weights from models/StableDiffusion/stable-diffusion-v1-5/unet ...

### missing keys: 560; 
### unexpected keys: 0;
### Motion Module Parameters: 417.1376 M
```

What could be the reason for the presence of missing keys?

**Comment by lckj2009** [comment]
The same situation applies to me here as well

**Comment by liutaocode** [comment]
Those are parameters of the motion module, which is not included in the original Unet.

**Comment by song-wensong** [comment]
@liutaocode Thank you!

**Comment by luyibo20040205** [comment]
> @liutaocode Thank you!

@song-wensong So can I just ignore these missing keys? Or what should I do to fix it?

**Comment by liutaocode** [comment]
Ignoring them is fine.

> > @liutaocode Thank you!
> 
> @song-wensong So can I just ignore these missing keys? Or what should I do to fix it?
