### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Cubey42** [guoyww/AnimateDiff#26]
after banging my head with other issues, I'm now stuck here:
(animatediff) PS I:\AnimateDiff\AnimateDiff> python -m scripts.animate --config configs/prompts/1-ToonYou.yaml
loaded temporal unet's pretrained weights from models/StableDiffusion/stable-diffusion-v1-5\unet ...
### Temporal Module Parameters: 417.1376 M
Traceback (most recent call last):
  File "C:\Users\Lucas\miniconda3\envs\animatediff\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Lucas\miniconda3\envs\animatediff\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "I:\AnimateDiff\AnimateDiff\scripts\animate.py", line 159, in <module>
    main(args)
  File "I:\AnimateDiff\AnimateDiff\scripts\animate.py", line 56, in main
    else: assert False
AssertionError

**Comment by asmjo** [comment]
> after banging my head with other issues, I'm now stuck here: (animatediff) PS I:\AnimateDiff\AnimateDiff> python -m scripts.animate --config configs/prompts/1-ToonYou.yaml loaded temporal unet's pretrained weights from models/StableDiffusion/stable-diffusion-v1-5\unet ...
> 
> ### missing keys: 560;
> ### unexpected keys: 0;
> ### Temporal Module Parameters: 417.1376 M
> Traceback (most recent call last): File "C:\Users\Lucas\miniconda3\envs\animatediff\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Users\Lucas\miniconda3\envs\animatediff\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "I:\AnimateDiff\AnimateDiff\scripts\animate.py", line 159, in main(args) File "I:\AnimateDiff\AnimateDiff\scripts\animate.py", line 56, in main else: assert False AssertionError

Stuck at the same part. Did you solve it?
