### ISSUE TITLE
Poor Video Quality When Using Depth-Generated Images in RGB sparsectrl

### ISSUE THREAD

**Issue by chuck-ma** [guoyww/AnimateDiff#274]
The dreambooth model i use: meinamix_meinaV11

When using RGB sparsectrl, if the first frame is selected from images generated through controlnets like depth, the resulting video quality is poor.

![image_out](https://github.com/guoyww/AnimateDiff/assets/74402255/32b4a966-dc4d-4aa6-863f-7e59a3df6c8c)

![14bb5744-0d96-4599-b52b-825f72050536](https://github.com/guoyww/AnimateDiff/assets/74402255/9d3d84ca-0b50-4ff6-b90a-8c4a3009a459)

However, if the first frame is selected from images generated through text by dreambooth model , the resulting video quality is much better.

![1 (1)](https://github.com/guoyww/AnimateDiff/assets/74402255/9fc29bb0-e23c-4779-82e0-8e29a59479db)

![59f3663e-b857-4c91-bc95-0db9a676eac5](https://github.com/guoyww/AnimateDiff/assets/74402255/e67da1f7-5020-47c3-b879-47146c34540b)

**Comment by chuck-ma** [comment]
I've identified the cause of my issue.

**Comment by vicitooo** [comment]
Can you share the solution with us?
