### ISSUE TITLE
【来自动画行业建议】NICE!从它身上我看到了AI RENDER的可能

### ISSUE THREAD

**Issue by Yorha4D** [guoyww/AnimateDiff#3]
作为专业向使用，建议能够接入一些像Blender这样的生产软件中，只靠Gradio Interface这样的不是很适合于生产
![image](https://github.com/guoyww/AnimateDiff/assets/116185401/7693c1d0-a468-432c-8578-60232f934776)

如图，这是我在Blender接入了ComfyUI，3D软件可以input更精确的数据（而不是预处理器的不稳定计算），效果会更好，同时也更符合当前动画生产的需求

**Comment by Yorha4D** [comment]
@guoyww

**Comment by guoyww** [comment]
感谢支持，希望多交流~ @Yorha4D

**Comment by Yorha4D** [comment]
> 感谢支持，希望多交流~ @Yorha4D

@guoyww 好的期待未来发展(加油啦~)
