### ISSUE TITLE
ModuleNotFoundError: No module named 'animatediff'

### ISSUE THREAD

**Issue by xdomiall** [guoyww/AnimateDiff#32]
Hi everyone,
Running Windows 10 x64, followed the instructions for python, I am getting:
```
(animatediff) C:\Apps\AnimateDiff\scripts>python -m animate --config configs\prompts\10-InitImageYoimiya.yml
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Apps\AnimateDiff\scripts\animate.py", line 15, in <module>
    from animatediff.models.unet import UNet3DConditionModel
ModuleNotFoundError: No module named 'animatediff'
```
![image](https://github.com/guoyww/AnimateDiff/assets/42623148/fecdc633-5bde-4455-b22d-d606c4352515)

Any help will be greatly appreciated! Thank you

**Comment by xdomiall** [comment]
Consider this closed please, I've overwritten the repo files when creating venv

**Comment by Novalien0424** [comment]
Hello I run into the same problem now, can you tell me how you solved this?
