### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by Int37** [guoyww/AnimateDiff#34]
Traceback (most recent call last):
  File "/home/dmitry/miniconda3/envs/animatediff/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dmitry/miniconda3/envs/animatediff/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/f/project/stable_animation/AnimateDiff/scripts/animate.py", line 159, in <module>
    main(args)
  File "/mnt/f/project/stable_animation/AnimateDiff/scripts/animate.py", line 51, in main
    text_encoder = CLIPTextModel.from_pretrained(args.pretrained_model_path, subfolder="text_encoder")
  File "/home/dmitry/miniconda3/envs/animatediff/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2230, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/dmitry/miniconda3/envs/animatediff/lib/python3.10/site-packages/transformers/modeling_utils.py", line 386, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

Did everything according to the instructions, what could be the problem? Perhaps I missed something?

**Comment by Int37** [comment]
run command:  python -m scripts.animate --config configs/prompts/2-Lyriel.yaml  --pretrained_model_path="models/StableDiffusion"

**Comment by SSUHan** [comment]
downloaded file of sd 1.5 could be corruped. 

In my case, re-downloading fixed this issue. 

See [https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8123](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8123)

**Comment by Int37** [comment]
@SSUHan Yes, you are right, I did not expect that it would be necessary to download absolutely all models from https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main?doi=true, I thought it would be enough only the original stable diffusion model. My thanks

**Comment by StableInfo** [comment]
Hello to you all @Int37  @SSUHan , 
can you give me a screenshot of your config inside the "webUI" that was made by the animatediff team?
(In particular what path value did you insert here : "Model checkpoints (select pretrained model path first)." ??)

I would also like to see what did you put inside the models folder, here is what I have:
![image](https://github.com/guoyww/AnimateDiff/assets/136593585/60c89d1e-398c-432b-a0ed-b87f0d862723)

And whenever I go the UI and try to select a value for the models path I get an error:
![image](https://github.com/guoyww/AnimateDiff/assets/136593585/00d0cbe3-101b-46b8-ab27-2c6b94e4795d)

Thanks

**Comment by qburst-fidha** [comment]
I am facing same issue. Any solution?

**Comment by JoshonSmith** [comment]
I am facing same issue. Any solution?

    with safe_open(lora_path, framework='pt', device='cpu') as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

**Comment by qburst-fidha** [comment]
> I am facing same issue. Any solution?
> 
> ```
> with safe_open(lora_path, framework='pt', device='cpu') as f:
> ```
> 
> safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

The '.safetensors' model as an adapter didn't work for me. Instead, I used the '.bin' adapter model to load it into the TextGen UI.
