### ISSUE TITLE
what's the different with base and path?

### ISSUE THREAD

**Issue by didoll-john** [guoyww/AnimateDiff#35]
Not very sure about this
NewModel:
  path: "[path to your DreamBooth/LoRA model .safetensors file]"
  base: "[path to LoRA base model .safetensors file, leave it empty string if not needed]"

In Ghibli example case
GhibliBackground:
  base: "models/DreamBooth_LoRA/CounterfeitV30_25.safetensors"
  path: "models/DreamBooth_LoRA/lora_Ghibli_n3.safetensors"
it seems like the base means the base model, and the path means the lora, but in other example like
ToonYou:
  base: ""
  path: "models/DreamBooth_LoRA/toonyou_beta3.safetensors"

so I try to change it to like this, something goes strange
  base: "models/DreamBooth_LoRA/toonyou_beta3.safetensors"
  path: ""
I got this 
![sample](https://github.com/guoyww/AnimateDiff/assets/134175197/a10c15f8-1047-486b-9e55-a38fa09f44ea)

It's not the style of Toonyou, I don't know.

And I did another try, I set the prompt like:
  base: "models/DreamBooth_LoRA/toonyou_beta3.safetensors"
  path: "models/DreamBooth_LoRA/smv1-10.safetensors"
the smv1-10.safetensors is a lora download from civitai, then I got an error.
omegaconf.errors.ConfigAttributeError: Missing key lora_alpha
    full_key: ToonYou.lora_alpha
    object_type=dict

so what's the different with base and path, and how to set it correct?

**Comment by guoyww** [comment]
Sorry for this confusion. @didoll-john 

- ***In case you use Dreambooth***:
      "path" is the path to your DreamBooth checkpoint
      "base" should be an empty string

- ***In case you use LoRA***:
      "path" is the path to your LoRA checkpoint
      "base" is the path to the LoRA base model (probably a DreamBooth checkpoint)

**Comment by didoll-john** [comment]
got it!
Thanks so much!
