### ISSUE TITLE
Gradio App is broken

### ISSUE THREAD

**Issue by clark-tax** [guoyww/AnimateDiff#354]
Gradio code app code is no longer compatible with the latest version of gradio. Environment file does not specify a gradio version, so the latest version is automatically downloaded.  For example, latest version of gradio apparently no longer supports `Dropdown.update()`

**Comment by ligenxun** [comment]
the same to you

**Comment by guoyww** [comment]
Just update a new `requirements.txt` with the specified version. The Gradio version should be `3.36.1`
