### ISSUE TITLE
 from diffusers.utils import DIFFUSERS_CACHE, SAFETENSORS_WEIGHTS_NAME, WEIGHTS_NAME, is_safetensors_available ImportError: cannot import name 'DIFFUSERS_CACHE' from 'diffusers.utils' 

### ISSUE THREAD

**Issue by wyyfffff** [guoyww/AnimateDiff#367]
from diffusers.utils import DIFFUSERS_CACHE, SAFETENSORS_WEIGHTS_NAME, WEIGHTS_NAME, is_safetensors_available ImportError: cannot import name 'DIFFUSERS_CACHE' from 'diffusers.utils' 

Which version of diffusers should I install? I try on 0.11.1 and newest version

**Comment by guoyww** [comment]
Hi @wyyfffff , this repo has been tested on diffusers 0.11.1 and I think you may try this version first.

**Comment by LukeLIN-web** [comment]
Does diffusers remove this ?
