### ISSUE TITLE
GIF with diffusion noise only

### ISSUE THREAD

**Issue by ekiwi111** [guoyww/AnimateDiff#48]
Got any ideas where I should start looking to figure out why the resulting GIF is just jittery diffusion noise and nothing else? Much appreciated!

<img src="https://github.com/guoyww/AnimateDiff/assets/13213650/f3eb6659-b5bd-444d-8b75-6a0701bddff9" width="250">

Could this issue be related to the sampler being used? Is there a possibility to choose a different sampler?

cc @talesofai, that's related to this fork - https://github.com/talesofai/AnimateDiff 
P.S. I'm facing this with original repo too

**Comment by Enferlain** [comment]
Same, what is causing this?

**Comment by ykk648** [comment]
normally it's caused by image inverse noise with too much diffusion loops

**Comment by Enferlain** [comment]
Was fixed after switching models I think

**Comment by ekiwi111** [comment]
Resolved by itself after some time. I can't provide any resolution steps unfortunately.
