### ISSUE TITLE
A1111 extension available

### ISSUE THREAD

**Issue by continue-revolution** [guoyww/AnimateDiff#56]
I am the author of the [SAM extension](https://github.com/continue-revolution/sd-webui-segment-anything) and I wrote one extension for AnimateDiff.

https://github.com/continue-revolution/sd-webui-animatediff

Have fun with it!

**Comment by hafiidz** [comment]
Do you have the min GPU ram amount required to run that ya? I have an 8GB 1070ti.

**Comment by IntellectzProductions** [comment]
Is not working. It creates a grid and then that's it. The folder where the gif is supposed to be stays empty. Maybe you can tell me what I need to do.

**Comment by p0mad** [comment]
@continue-revolution 
is it possible to use this alongside Controlnet Pose for generating videos?

**Comment by continue-revolution** [comment]
@p0mad Please post an issue/discussion there, and I will try when I have time to test. You can also test on your own and let me know.

For everybody else who come here, if your question is specifically about the A1111 extension, please post your question/request/issue there and I will make sure to respond. It is hard to track issues in 2 different places.
