### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by babypotatotang** [guoyww/AnimateDiff#68]
Hi! 
I'm really impressed with your work. I want to train the model with my dataset, 

Are there any plans to release the training code?

Thanks again

**Comment by x-CK-x** [comment]
same.

**Comment by x-CK-x** [comment]
I've noticed that **some** full fine-tuned models using data from specific image boards struggle quite a lot with the _motion models_. I believe that this has a lot to do with tag alignment; as tag's from specific image boards likely don't align well with the tags from the original dataset in the paper.

@guoyww I'm curious to hear what your opinion on this is and if there is a proposed release date of training scripts?

~thanks

**Comment by howardgriffin** [comment]
Waiting for your training code...

**Comment by Katehuuh** [comment]
training code: https://github.com/tumurzakov/AnimateDiff

**Comment by vicentowang** [comment]
> training code: https://github.com/tumurzakov/AnimateDiff

have you trained it for experiment ?

**Comment by Katehuuh** [comment]
Yes.

**Comment by x-CK-x** [comment]
> > training code: https://github.com/tumurzakov/AnimateDiff
> 
> I tried this code but the finetune results are bad :(

could you elaborate on this a bit?
I'm curious to know

**Comment by limbo0000** [comment]
Released. Thanks.
