### ISSUE TITLE
How to use custom diffusers format?

### ISSUE THREAD

**Issue by howardgriffin** [guoyww/AnimateDiff#71]
The current custom model are in ckpt or safetensors format, but how to use  diffusers format? Will you support the diffusers format in the future?

**Comment by actionless** [comment]
i've tried commenting out the code which loading safetensors on top of base model, and replaced base model path to model saved from diffusers - and seems to work

however it made the frames not connected to each other

i'm still investigating - mb the reason that Motion Module is SD 1.5 and my custom base model is absed on sd 2.1

**Comment by actionless** [comment]
yeah - i've tried with my other custom model, this this time based on sd 1.5:

and it works better - frames connected now, although result still not as nice as on demos - looking further into it

**Comment by actionless** [comment]
yeah, it was just overtrained model, i tried another custom model saved from diffusers (based on sd 1.5 too) - and it works well as expected

**Comment by howardgriffin** [comment]
> ommenting out the code which loading safetensors on top of base model,

Thank you, this modification actually works well

**Comment by howardgriffin** [comment]
> i've tried commenting out the code which loading safetensors on top of base model, and replaced base model path to model saved from diffusers - and seems to work
> 
> however it made the frames not connected to each other
> 
> i'm still investigating - mb the reason that Motion Module is SD 1.5 and my custom base model is absed on sd 2.1

Thank you, this modification actually works well
