### ISSUE TITLE
Can I use multiple graphics cards for reasoning?

### ISSUE THREAD

**Issue by RuaYiii** [guoyww/AnimateDiff#90]
I didn't find a profile where I could obviously select the number of graphics cards.
What's awkward is that I own RTX3080 *2, and I don't have enough video memory on a single card.

I'd like to ask where I can turn on multiple graphics cards ? , and will this feature be added in the future?

**Comment by threeal** [comment]
In case of not having enough video memory, I suggest ensuring that [xformer](https://github.com/facebookresearch/xformers) is installed.

![image](https://github.com/guoyww/AnimateDiff/assets/10202888/7ff1e626-dad0-475c-b505-28f8c0badc7b)

**Comment by RuaYiii** [comment]
> In case of not having enough video memory, I suggest ensuring that [xformer](https://github.com/facebookresearch/xformers) is installed.
> 
> ![image](https://user-images.githubusercontent.com/10202888/256097065-7ff1e626-dad0-475c-b505-28f8c0badc7b.png)

But I made sure I followed xformer, and my question is: Is it possible to use multi-graphics reasoning?
Because I can't get enough out of a single card.

**Comment by x-CK-x** [comment]
https://github.com/guoyww/AnimateDiff/issues/78

**Comment by RuaYiii** [comment]
> #78

Thanks !!!
