### ISSUE TITLE
Support latest diffuser version

### ISSUE THREAD

**Issue by LaLaLailalai** [guoyww/AnimateDiff#95]
Hi @guoyww,  
if this project can support the latest diffusers like diffusers v0.17?

I would like to use this great project with diffusers v0.17, but I have run into several issues with mismatched functions and classes. I was wondering if you have any advice on how to resolve them.

**Comment by guoyww** [comment]
Hi @LaLaLailalai . We will update the repo to newer `diffusers` in the future. Different `diffusers` versions define some layers/functions at different files, and you may pay attention to these changes. Thanks.

**Comment by akk-123** [comment]
@guoyww  3 months have passed, when will support latest diffuser version??

**Comment by SystemErrorWang** [comment]
+1
would also like to see animatediff with lateset diffusers. Many api and functions have changed since diffusers 0.11, making it extremely difficult to develop new applications based on animatediff
